### ISSUE TITLE
Wrong error message when trying to re-register with existing account.

### ISSUE THREAD

**Issue by dobos** [sciserver/login-portal#13]
Instead of a message saying username is taken the following is displayed:

Response status code does not indicate success: 401 (Unauthorized).

**Comment by dmedv** [comment]
What happens, I believe, is this:
- it looks for a CasJobs user with the same name (and finds it);
- it tries to authenticate (in CasJobs, not in Keystone) with the password you provided in the registration form; the password does not match the old CasJobs password, so 401 is returned.

401 response is the correct one, but I agree that the error message is a bit confusing. I could change it to something like: "Failed to authenticate with CasJobs using an existing username".

**Comment by dmedv** [comment]
... but I should probably check if a Keystone user with the same name exists, before trying to authenticate with CasJobs.

**Comment by dmedv** [comment]
It will now display this error message: "User name already exists". Deployed the updated version to scitest02. Marking as fixed.

**Comment by dmedv** [comment]
Deployed to test.preprod

**Comment by knservis** [comment]
Has this been deployed? I just got the same error
