### ISSUE TITLE
Icons on login portal with links display wrong cursor

### ISSUE THREAD

**Issue by dobos** [sciserver/login-portal#14]
After logging in the list of services on the right side of the login portal are clickable but text selection cursor is displayed instead of the usual hand. This might be confusing to some.

**Comment by bonbons0220** [comment]
I added a line to the .less file to show a pointer in those boxes, and I
created a pull request. It won't show up until someone builds the css file.
It's a really minor fix, so maybe next time Dmitry is fixing another bug he
can rebuild the css.

Bonnie Souter PhD

Associate Research Scientist

Institute for Data Intensive Engineering and Science

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by dmedv** [comment]
I have merged Bonnie's changes and rebuilt the CSS. You can test the updated version on scitest02 now. Looks ok to me, the cursor has changed. Marking as fixed.

**Comment by dmedv** [comment]
Deployed to test.preprod
