### ISSUE TITLE
Can't re-register with CasJobs account if existing password isn't strong enogh

### ISSUE THREAD

**Issue by dobos** [sciserver/login-portal#15]
Hi Mitya,

I used to have a fairly simple 4-character password for casjobs and the login portal won't let me re-register with the error message:

The Password must be at least 5 characters long.

If I enter a new password, it says my account already exists which is correct behavior.

-L

**Comment by bonbons0220** [comment]
I think Ani has to reset your password.

Bonnie Souter PhD

Associate Research Scientist

Institute for Data Intensive Engineering and Science

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by dmedv** [comment]
I can take care of it. I'll send Laszlo his new password.
