### ISSUE TITLE
incorrect hyperlink on sciserver's login portal page(http://www.sciserver.org/tools/portal/)

### ISSUE THREAD

**Issue by jkim485** [sciserver/login-portal#16]
The hyperlink of 'Go to the Portal' is 'compute.sciserver.org' instead of 'portal.sciserver.org'.
The hyperlink of the icon is correct.

**Comment by mtaghiza** [comment]
could you guys fix as well another broken link in http://www.sciserver.org/tools/portal/ http://www.sciserver.org/tools/skyserver/ ?

Also, a noticeable link to the login-portal (or to a web page listing the apps) should be placed in the sciserver.org homepage. Some users (that have not used sciserver tools before) have already mentioned that it is not easy to log into sciserver (or use the tools), in the case when they get into sciserver.org as an entry point.

**Comment by bonbons0220** [comment]
Fixed Got to the Portal link.

> could you guys fix as well another broken link in http://www.sciserver.org/tools/portal/ http://www.sciserver.org/tools/skyserver/ ?

This is not a broken link, unless I'm misunderstanding something.

**Comment by bsouter** [comment]
Issues with www.sciserver.org should be raised in
https://github.com/sciserver/SciServer-WordPress-Website. Anyhow, fixed
first broken. Second thing is not a broken link. Also added a Login to
SciServer button to front page of website.

Cheers,
Bonnie

Bonnie Souter PhD

Associate Research Scientist

Institute for Data Intensive Engineering and Science

Johns Hopkins University

3200 N Charles Street

Baltimore, MD 21218

(w) 410-516-2011

(c)  410-262-5245

bsouter@jhu.edu

**Comment by mtaghiza** [comment]
thanks, the link to the portal looks good. 
the second issue is that the link to Skyserver is missing in the text "Go to SkyServer", right below the skyserver icon, in page http://www.sciserver.org/tools/skyserver

**Comment by bonbons0220** [comment]
Fixed
