### ISSUE TITLE
Creating new user in Portal hangs forever

### ISSUE THREAD

**Issue by raddick** [sciserver/login-portal#4]
When I try to create a new user, the portal hangs. See:

http://scitest09.pha.jhu.edu/login-portal/register

The Register button turns blue instead of gray and the "circle-arrow" glyph appears on the Register button, but nothing else happens. Finally I have to close the browser window.

This happens with every browser I have tried: Chrome, Firefox, and IE on Windows and Chrome and Firefox on Mac.

**Comment by raddick** [comment]
Update: after about 2 minutes, the page is replaced with an error message: "Error: Some error has occurred"

**Comment by jkim485** [comment]
Similar problem reported on https://github.com/idies/scidrive-ui/issues/6

**Comment by raddick** [comment]
Update 6/23/2015 10 AM: Registering a new user worked for me this morning, and I was able to create a user called raddick. 

But now it's broken again, in all browsers, with the same "Some error has occurred" error message.
